# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create temp folder
      run: |
        mkdir /home/runner/work/_temp_files
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Test with pytest (including test coverage)
      run: |
        pytest --cov-report xml:coverage.xml --cov=.
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
